#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    #STOW_FOLDERS="nvim,vim,bin,tmux,zsh,gitconfig"
    STOW_FOLDERS="nvim,bin,tmux,zsh,gitconfig"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES="$(dirname "$(readlink -f "$0")")"
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
